apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: infra-challenge
image: rancher/k3s:v1.36.0-k3s1
servers: 1
agents: 1
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5001"
ports:
  - port: 8081:80
    nodeFilters:
      - loadbalancer
  - port: 3000:30080
    nodeFilters:
      - server:0
options:
  k3d:
    wait: true
    timeout: "60s"
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
