image:
  repository: "532287339094.dkr.ecr.eu-central-1.amazonaws.com/hm-dev-greeter"
  tag: "ca697e3b07e4631a5db42e0d8306496ca243f3d9"
helloTag: "ca697e3b07e4631a5db42e0d8306496ca243f3d9"
buildTime: "2026-05-20T11:05:21Z"
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
