image:
  repository: "532287339094.dkr.ecr.eu-central-1.amazonaws.com/hm-dev-greeter"
  tag: "88c4ed56635096d08b9a606f2c13fa1acfdeda33"
helloTag: "88c4ed56635096d08b9a606f2c13fa1acfdeda33"
buildTime: "2026-05-20T21:10:27Z"
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
